version: "3.7"

services:
  db:
    env_file: .env
    image: postgres:10.6-alpine
    volumes:
      - pg.10.6:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  signature-api:
    build: .
    command: ruby app.rb
    volumes:
      - .:/signature:cached
    ports:
      - 4567:4567

    tty: true
    stdin_open: true

volumes:
  pg.10.6:
    external: true